<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
$array = [
            ['name' => 'MEDELLÍN', 'codigo_dane' => '05001'],
            ['name' => 'ABEJORRAL', 'codigo_dane' => '05002'],
            ['name' => 'ABRIAQUÍ', 'codigo_dane' => '05004'],
            ['name' => 'ALEJANDRÍA', 'codigo_dane' => '05021'],
            ['name' => 'AMAGÁ', 'codigo_dane' => '05030'],
            ['name' => 'AMALFI', 'codigo_dane' => '05031'],
            ['name' => 'ANDES', 'codigo_dane' => '05034'],
            ['name' => 'ANGELÓPOLIS', 'codigo_dane' => '05036'],
            ['name' => 'ANGOSTURA', 'codigo_dane' => '05038'],
            ['name' => 'ANORÍ', 'codigo_dane' => '05040'],
            ['name' => 'SANTA FÉ DE ANTIOQUIA', 'codigo_dane' => '05042'],
            ['name' => 'ANZÁ', 'codigo_dane' => '05044'],
            ['name' => 'APARTADÓ', 'codigo_dane' => '05045'],
            ['name' => 'ARBOLETES', 'codigo_dane' => '05051'],
            ['name' => 'ARGELIA', 'codigo_dane' => '05055'],
            ['name' => 'ARMENIA', 'codigo_dane' => '05059'],
            ['name' => 'BARBOSA', 'codigo_dane' => '05079'],
            ['name' => 'BELMIRA', 'codigo_dane' => '05086'],
            ['name' => 'BELLO', 'codigo_dane' => '05088'],
            ['name' => 'BETANIA', 'codigo_dane' => '05091'],
            ['name' => 'BETULIA', 'codigo_dane' => '05093'],
            ['name' => 'CIUDAD BOLÍVAR', 'codigo_dane' => '05101'],
            ['name' => 'BRICEÑO', 'codigo_dane' => '05107'],
            ['name' => 'BURITICÁ', 'codigo_dane' => '05113'],
            ['name' => 'CÁCERES', 'codigo_dane' => '05120'],
            ['name' => 'CAICEDO', 'codigo_dane' => '05125'],
            ['name' => 'CALDAS', 'codigo_dane' => '05129'],
            ['name' => 'CAMPAMENTO', 'codigo_dane' => '05134'],
            ['name' => 'CAÑASGORDAS', 'codigo_dane' => '05138'],
            ['name' => 'CARACOLÍ', 'codigo_dane' => '05142'],
            ['name' => 'CARAMANTA', 'codigo_dane' => '05145'],
            ['name' => 'CAREPA', 'codigo_dane' => '05147'],
            ['name' => 'EL CARMEN DE VIBORAL', 'codigo_dane' => '05148'],
            ['name' => 'CAROLINA', 'codigo_dane' => '05150'],
            ['name' => 'CAUCASIA', 'codigo_dane' => '05154'],
            ['name' => 'CHIGORODÓ', 'codigo_dane' => '05172'],
            ['name' => 'CISNEROS', 'codigo_dane' => '05190'],
            ['name' => 'COCORNÁ', 'codigo_dane' => '05197'],
            ['name' => 'CONCEPCIÓN', 'codigo_dane' => '05206'],
            ['name' => 'CONCORDIA', 'codigo_dane' => '05209'],
            ['name' => 'COPACABANA', 'codigo_dane' => '05212'],
            ['name' => 'DABEIBA', 'codigo_dane' => '05234'],
            ['name' => 'DONMATÍAS', 'codigo_dane' => '05237'],
            ['name' => 'EBÉJICO', 'codigo_dane' => '05240'],
            ['name' => 'EL BAGRE', 'codigo_dane' => '05250'],
            ['name' => 'ENTRERRÍOS', 'codigo_dane' => '05264'],
            ['name' => 'ENVIGADO', 'codigo_dane' => '05266'],
            ['name' => 'FREDONIA', 'codigo_dane' => '05282'],
            ['name' => 'FRONTINO', 'codigo_dane' => '05284'],
            ['name' => 'GIRALDO', 'codigo_dane' => '05306'],
            ['name' => 'GIRARDOTA', 'codigo_dane' => '05308'],
            ['name' => 'GÓMEZ PLATA', 'codigo_dane' => '05310'],
            ['name' => 'GRANADA', 'codigo_dane' => '05313'],
            ['name' => 'GUADALUPE', 'codigo_dane' => '05315'],
            ['name' => 'GUARNE', 'codigo_dane' => '05318'],
            ['name' => 'GUATAPÉ', 'codigo_dane' => '05321'],
            ['name' => 'HELICONIA', 'codigo_dane' => '05347'],
            ['name' => 'HISPANIA', 'codigo_dane' => '05353'],
            ['name' => 'ITAGÜÍ', 'codigo_dane' => '05360'],
            ['name' => 'ITUANGO', 'codigo_dane' => '05361'],
            ['name' => 'JARDÍN', 'codigo_dane' => '05364'],
            ['name' => 'JERICÓ', 'codigo_dane' => '05368'],
            ['name' => 'LA CEJA', 'codigo_dane' => '05376'],
            ['name' => 'LA ESTRELLA', 'codigo_dane' => '05380'],
            ['name' => 'LA PINTADA', 'codigo_dane' => '05390'],
            ['name' => 'LA UNIÓN', 'codigo_dane' => '05400'],
            ['name' => 'LIBORINA', 'codigo_dane' => '05411'],
            ['name' => 'MACEO', 'codigo_dane' => '05425'],
            ['name' => 'MARINILLA', 'codigo_dane' => '05440'],
            ['name' => 'MONTEBELLO', 'codigo_dane' => '05467'],
            ['name' => 'MURINDÓ', 'codigo_dane' => '05475'],
            ['name' => 'MUTATÁ', 'codigo_dane' => '05480'],
            ['name' => 'NARIÑO', 'codigo_dane' => '05483'],
            ['name' => 'NECOCLÍ', 'codigo_dane' => '05490'],
            ['name' => 'NECHÍ', 'codigo_dane' => '05495'],
            ['name' => 'OLAYA', 'codigo_dane' => '05501'],
            ['name' => 'PEÑOL', 'codigo_dane' => '05541'],
            ['name' => 'PEQUE', 'codigo_dane' => '05543'],
            ['name' => 'PUEBLORRICO', 'codigo_dane' => '05576'],
            ['name' => 'PUERTO BERRÍO', 'codigo_dane' => '05579'],
            ['name' => 'PUERTO NARE', 'codigo_dane' => '05585'],
            ['name' => 'PUERTO TRIUNFO', 'codigo_dane' => '05591'],
            ['name' => 'REMEDIOS', 'codigo_dane' => '05604'],
            ['name' => 'RETIRO', 'codigo_dane' => '05607'],
            ['name' => 'RIONEGRO', 'codigo_dane' => '05615'],
            ['name' => 'SABANALARGA', 'codigo_dane' => '05628'],
            ['name' => 'SABANETA', 'codigo_dane' => '05631'],
            ['name' => 'SALGAR', 'codigo_dane' => '05642'],
            ['name' => 'SAN ANDRÉS DE CUERQUÍA', 'codigo_dane' => '05647'],
            ['name' => 'SAN CARLOS', 'codigo_dane' => '05649'],
            ['name' => 'SAN FRANCISCO', 'codigo_dane' => '05652'],
            ['name' => 'SAN JERÓNIMO', 'codigo_dane' => '05656'],
            ['name' => 'SAN JOSÉ DE LA MONTAÑA', 'codigo_dane' => '05658'],
            ['name' => 'SAN JUAN DE URABÁ', 'codigo_dane' => '05659'],
            ['name' => 'SAN LUIS', 'codigo_dane' => '05660'],
            ['name' => 'SAN PEDRO DE LOS MILAGROS', 'codigo_dane' => '05664'],
            ['name' => 'SAN PEDRO DE URABÁ', 'codigo_dane' => '05665'],
            ['name' => 'SAN RAFAEL', 'codigo_dane' => '05667'],
            ['name' => 'SAN ROQUE', 'codigo_dane' => '05670'],
            ['name' => 'SAN VICENTE FERRER', 'codigo_dane' => '05674'],
            ['name' => 'SANTA BÁRBARA', 'codigo_dane' => '05679'],
            ['name' => 'SANTA ROSA DE OSOS', 'codigo_dane' => '05686'],
            ['name' => 'SANTO DOMINGO', 'codigo_dane' => '05690'],
            ['name' => 'EL SANTUARIO', 'codigo_dane' => '05697'],
            ['name' => 'SEGOVIA', 'codigo_dane' => '05736'],
            ['name' => 'SONSÓN', 'codigo_dane' => '05756'],
            ['name' => 'SOPETRÁN', 'codigo_dane' => '05761'],
            ['name' => 'TÁMESIS', 'codigo_dane' => '05789'],
            ['name' => 'TARAZÁ', 'codigo_dane' => '05790'],
            ['name' => 'TARSO', 'codigo_dane' => '05792'],
            ['name' => 'TITIRIBÍ', 'codigo_dane' => '05809'],
            ['name' => 'TOLEDO', 'codigo_dane' => '05819'],
            ['name' => 'TURBO', 'codigo_dane' => '05837'],
            ['name' => 'URAMITA', 'codigo_dane' => '05842'],
            ['name' => 'URRAO', 'codigo_dane' => '05847'],
            ['name' => 'VALDIVIA', 'codigo_dane' => '05854'],
            ['name' => 'VALPARAÍSO', 'codigo_dane' => '05856'],
            ['name' => 'VEGACHÍ', 'codigo_dane' => '05858'],
            ['name' => 'VENECIA', 'codigo_dane' => '05861'],
            ['name' => 'VIGÍA DEL FUERTE', 'codigo_dane' => '05873'],
            ['name' => 'YALÍ', 'codigo_dane' => '05885'],
            ['name' => 'YARUMAL', 'codigo_dane' => '05887'],
            ['name' => 'YOLOMBÓ', 'codigo_dane' => '05890'],
            ['name' => 'YONDÓ', 'codigo_dane' => '05893'],
            ['name' => 'ZARAGOZA', 'codigo_dane' => '05895'],
            ['name' => 'BARRANQUILLA', 'codigo_dane' => '08001'],
            ['name' => 'BARANOA', 'codigo_dane' => '08078'],
            ['name' => 'CAMPO DE LA CRUZ', 'codigo_dane' => '08137'],
            ['name' => 'CANDELARIA', 'codigo_dane' => '08141'],
            ['name' => 'GALAPA', 'codigo_dane' => '08296'],
            ['name' => 'JUAN DE ACOSTA', 'codigo_dane' => '08372'],
            ['name' => 'LURUACO', 'codigo_dane' => '08421'],
            ['name' => 'MALAMBO', 'codigo_dane' => '08433'],
            ['name' => 'MANATÍ', 'codigo_dane' => '08436'],
            ['name' => 'PALMAR DE VARELA', 'codigo_dane' => '08520'],
            ['name' => 'PIOJÓ', 'codigo_dane' => '08549'],
            ['name' => 'POLONUEVO', 'codigo_dane' => '08558'],
            ['name' => 'PONEDERA', 'codigo_dane' => '08560'],
            ['name' => 'PUERTO COLOMBIA', 'codigo_dane' => '08573'],
            ['name' => 'REPELÓN', 'codigo_dane' => '08606'],
            ['name' => 'SABANAGRANDE', 'codigo_dane' => '08634'],
            ['name' => 'SABANALARGA', 'codigo_dane' => '08638'],
            ['name' => 'SANTA LUCÍA', 'codigo_dane' => '08675'],
            ['name' => 'SANTO TOMÁS', 'codigo_dane' => '08685'],
            ['name' => 'SOLEDAD', 'codigo_dane' => '08758'],
            ['name' => 'SUAN', 'codigo_dane' => '08770'],
            ['name' => 'TUBARÁ', 'codigo_dane' => '08832'],
            ['name' => 'USIACURÍ', 'codigo_dane' => '08849'],
            ['name' => 'BOGOTÁ, D.C.', 'codigo_dane' => '11001'],
            ['name' => 'CARTAGENA DE INDIAS', 'codigo_dane' => '13001'],
            ['name' => 'ACHÍ', 'codigo_dane' => '13006'],
            ['name' => 'ALTOS DEL ROSARIO', 'codigo_dane' => '13030'],
            ['name' => 'ARENAL', 'codigo_dane' => '13042'],
            ['name' => 'ARJONA', 'codigo_dane' => '13052'],
            ['name' => 'ARROYOHONDO', 'codigo_dane' => '13062'],
            ['name' => 'BARRANCO DE LOBA', 'codigo_dane' => '13074'],
            ['name' => 'CALAMAR', 'codigo_dane' => '13140'],
            ['name' => 'CANTAGALLO', 'codigo_dane' => '13160'],
            ['name' => 'CICUCO', 'codigo_dane' => '13188'],
            ['name' => 'CÓRDOBA', 'codigo_dane' => '13212'],
            ['name' => 'CLEMENCIA', 'codigo_dane' => '13222'],
            ['name' => 'EL CARMEN DE BOLÍVAR', 'codigo_dane' => '13244'],
            ['name' => 'EL GUAMO', 'codigo_dane' => '13248'],
            ['name' => 'EL PEÑÓN', 'codigo_dane' => '13268'],
            ['name' => 'HATILLO DE LOBA', 'codigo_dane' => '13300'],
            ['name' => 'MAGANGUÉ', 'codigo_dane' => '13430'],
            ['name' => 'MAHATES', 'codigo_dane' => '13433'],
            ['name' => 'MARGARITA', 'codigo_dane' => '13440'],
            ['name' => 'MARÍA LA BAJA', 'codigo_dane' => '13442'],
            ['name' => 'MONTECRISTO', 'codigo_dane' => '13458'],
            ['name' => 'SANTA CRUZ DE MOMPOX', 'codigo_dane' => '13468'],
            ['name' => 'MORALES', 'codigo_dane' => '13473'],
            ['name' => 'NOROSÍ', 'codigo_dane' => '13490'],
            ['name' => 'PINILLOS', 'codigo_dane' => '13549'],
            ['name' => 'REGIDOR', 'codigo_dane' => '13580'],
            ['name' => 'RÍO VIEJO', 'codigo_dane' => '13600'],
            ['name' => 'SAN CRISTÓBAL', 'codigo_dane' => '13620'],
            ['name' => 'SAN ESTANISLAO', 'codigo_dane' => '13647'],
            ['name' => 'SAN FERNANDO', 'codigo_dane' => '13650'],
            ['name' => 'SAN JACINTO', 'codigo_dane' => '13654'],
            ['name' => 'SAN JACINTO DEL CAUCA', 'codigo_dane' => '13655'],
            ['name' => 'SAN JUAN NEPOMUCENO', 'codigo_dane' => '13657'],
            ['name' => 'SAN MARTÍN DE LOBA', 'codigo_dane' => '13667'],
            ['name' => 'SAN PABLO', 'codigo_dane' => '13670'],
            ['name' => 'SANTA CATALINA', 'codigo_dane' => '13673'],
            ['name' => 'SANTA ROSA', 'codigo_dane' => '13683'],
            ['name' => 'SANTA ROSA DEL SUR', 'codigo_dane' => '13688'],
            ['name' => 'SIMITÍ', 'codigo_dane' => '13744'],
            ['name' => 'SOPLAVIENTO', 'codigo_dane' => '13760'],
            ['name' => 'TALAIGUA NUEVO', 'codigo_dane' => '13780'],
            ['name' => 'TIQUISIO', 'codigo_dane' => '13810'],
            ['name' => 'TURBACO', 'codigo_dane' => '13836'],
            ['name' => 'TURBANÁ', 'codigo_dane' => '13838'],
            ['name' => 'VILLANUEVA', 'codigo_dane' => '13873'],
            ['name' => 'ZAMBRANO', 'codigo_dane' => '13894'],
            ['name' => 'TUNJA', 'codigo_dane' => '15001'],
            ['name' => 'ALMEIDA', 'codigo_dane' => '15022'],
            ['name' => 'AQUITANIA', 'codigo_dane' => '15047'],
            ['name' => 'ARCABUCO', 'codigo_dane' => '15051'],
            ['name' => 'BELÉN', 'codigo_dane' => '15087'],
            ['name' => 'BERBEO', 'codigo_dane' => '15090'],
            ['name' => 'BETÉITIVA', 'codigo_dane' => '15092'],
            ['name' => 'BOAVITA', 'codigo_dane' => '15097'],
            ['name' => 'BOYACÁ', 'codigo_dane' => '15104'],
            ['name' => 'BRICEÑO', 'codigo_dane' => '15106'],
            ['name' => 'BUENAVISTA', 'codigo_dane' => '15109'],
            ['name' => 'BUSBANZÁ', 'codigo_dane' => '15114'],
            ['name' => 'CALDAS', 'codigo_dane' => '15131'],
            ['name' => 'CAMPOHERMOSO', 'codigo_dane' => '15135'],
            ['name' => 'CERINZA', 'codigo_dane' => '15162'],
            ['name' => 'CHINAVITA', 'codigo_dane' => '15172'],
            ['name' => 'CHIQUINQUIRÁ', 'codigo_dane' => '15176'],
            ['name' => 'CHISCAS', 'codigo_dane' => '15180'],
            ['name' => 'CHITA', 'codigo_dane' => '15183'],
            ['name' => 'CHITARAQUE', 'codigo_dane' => '15185'],
            ['name' => 'CHIVATÁ', 'codigo_dane' => '15187'],
            ['name' => 'CIÉNEGA', 'codigo_dane' => '15189'],
            ['name' => 'CÓMBITA', 'codigo_dane' => '15204'],
            ['name' => 'COPER', 'codigo_dane' => '15212'],
            ['name' => 'CORRALES', 'codigo_dane' => '15215'],
            ['name' => 'COVARACHÍA', 'codigo_dane' => '15218'],
            ['name' => 'CUBARÁ', 'codigo_dane' => '15223'],
            ['name' => 'CUCAITA', 'codigo_dane' => '15224'],
            ['name' => 'CUÍTIVA', 'codigo_dane' => '15226'],
            ['name' => 'CHÍQUIZA', 'codigo_dane' => '15232'],
            ['name' => 'CHIVOR', 'codigo_dane' => '15236'],
            ['name' => 'DUITAMA', 'codigo_dane' => '15238'],
            ['name' => 'EL COCUY', 'codigo_dane' => '15244'],
            ['name' => 'EL ESPINO', 'codigo_dane' => '15248'],
            ['name' => 'FIRAVITOBA', 'codigo_dane' => '15272'],
            ['name' => 'FLORESTA', 'codigo_dane' => '15276'],
            ['name' => 'GACHANTIVÁ', 'codigo_dane' => '15293'],
            ['name' => 'GÁMEZA', 'codigo_dane' => '15296'],
            ['name' => 'GARAGOA', 'codigo_dane' => '15299'],
            ['name' => 'GUACAMAYAS', 'codigo_dane' => '15317'],
            ['name' => 'GUATEQUE', 'codigo_dane' => '15322'],
            ['name' => 'GUAYATÁ', 'codigo_dane' => '15325'],
            ['name' => 'GÜICÁN DE LA SIERRA', 'codigo_dane' => '15332'],
            ['name' => 'IZA', 'codigo_dane' => '15362'],
            ['name' => 'JENESANO', 'codigo_dane' => '15367'],
            ['name' => 'JERICÓ', 'codigo_dane' => '15368'],
            ['name' => 'LABRANZAGRANDE', 'codigo_dane' => '15377'],
            ['name' => 'LA CAPILLA', 'codigo_dane' => '15380'],
            ['name' => 'LA VICTORIA', 'codigo_dane' => '15401'],
            ['name' => 'LA UVITA', 'codigo_dane' => '15403'],
            ['name' => 'VILLA DE LEYVA', 'codigo_dane' => '15407'],
            ['name' => 'MACANAL', 'codigo_dane' => '15425'],
            ['name' => 'MARIPÍ', 'codigo_dane' => '15442'],
            ['name' => 'MIRAFLORES', 'codigo_dane' => '15455'],
            ['name' => 'MONGUA', 'codigo_dane' => '15464'],
            ['name' => 'MONGUÍ', 'codigo_dane' => '15466'],
            ['name' => 'MONIQUIRÁ', 'codigo_dane' => '15469'],
            ['name' => 'MOTAVITA', 'codigo_dane' => '15476'],
            ['name' => 'MUZO', 'codigo_dane' => '15480'],
            ['name' => 'NOBSA', 'codigo_dane' => '15491'],
            ['name' => 'NUEVO COLÓN', 'codigo_dane' => '15494'],
            ['name' => 'OICATÁ', 'codigo_dane' => '15500'],
            ['name' => 'OTANCHE', 'codigo_dane' => '15507'],
            ['name' => 'PACHAVITA', 'codigo_dane' => '15511'],
            ['name' => 'PÁEZ', 'codigo_dane' => '15514'],
            ['name' => 'PAIPA', 'codigo_dane' => '15516'],
            ['name' => 'PAJARITO', 'codigo_dane' => '15518'],
            ['name' => 'PANQUEBA', 'codigo_dane' => '15522'],
            ['name' => 'PAUNA', 'codigo_dane' => '15531'],
            ['name' => 'PAYA', 'codigo_dane' => '15533'],
            ['name' => 'PAZ DE RÍO', 'codigo_dane' => '15537'],
            ['name' => 'PESCA', 'codigo_dane' => '15542'],
            ['name' => 'PISBA', 'codigo_dane' => '15550'],
            ['name' => 'PUERTO BOYACÁ', 'codigo_dane' => '15572'],
            ['name' => 'QUÍPAMA', 'codigo_dane' => '15580'],
            ['name' => 'RAMIRIQUÍ', 'codigo_dane' => '15599'],
            ['name' => 'RÁQUIRA', 'codigo_dane' => '15600'],
            ['name' => 'RONDÓN', 'codigo_dane' => '15621'],
            ['name' => 'SABOYÁ', 'codigo_dane' => '15632'],
            ['name' => 'SÁCHICA', 'codigo_dane' => '15638'],
            ['name' => 'SAMACÁ', 'codigo_dane' => '15646'],
            ['name' => 'SAN EDUARDO', 'codigo_dane' => '15660'],
            ['name' => 'SAN JOSÉ DE PARE', 'codigo_dane' => '15664'],
            ['name' => 'SAN LUIS DE GACENO', 'codigo_dane' => '15667'],
            ['name' => 'SAN MATEO', 'codigo_dane' => '15673'],
            ['name' => 'SAN MIGUEL DE SEMA', 'codigo_dane' => '15676'],
            ['name' => 'SAN PABLO DE BORBUR', 'codigo_dane' => '15681'],
            ['name' => 'SANTANA', 'codigo_dane' => '15686'],
            ['name' => 'SANTA MARÍA', 'codigo_dane' => '15690'],
            ['name' => 'SANTA ROSA DE VITERBO', 'codigo_dane' => '15693'],
            ['name' => 'SANTA SOFÍA', 'codigo_dane' => '15696'],
            ['name' => 'SATIVANORTE', 'codigo_dane' => '15720'],
            ['name' => 'SATIVASUR', 'codigo_dane' => '15723'],
            ['name' => 'SIACHOQUE', 'codigo_dane' => '15740'],
            ['name' => 'SOATÁ', 'codigo_dane' => '15753'],
            ['name' => 'SOCOTÁ', 'codigo_dane' => '15755'],
            ['name' => 'SOCHA', 'codigo_dane' => '15757'],
            ['name' => 'SOGAMOSO', 'codigo_dane' => '15759'],
            ['name' => 'SOMONDOCO', 'codigo_dane' => '15761'],
            ['name' => 'SORA', 'codigo_dane' => '15762'],
            ['name' => 'SOTAQUIRÁ', 'codigo_dane' => '15763'],
            ['name' => 'SORACÁ', 'codigo_dane' => '15764'],
            ['name' => 'SUSACÓN', 'codigo_dane' => '15774'],
            ['name' => 'SUTAMARCHÁN', 'codigo_dane' => '15776'],
            ['name' => 'SUTATENZA', 'codigo_dane' => '15778'],
            ['name' => 'TASCO', 'codigo_dane' => '15790'],
            ['name' => 'TENZA', 'codigo_dane' => '15798'],
            ['name' => 'TIBANÁ', 'codigo_dane' => '15804'],
            ['name' => 'TIBASOSA', 'codigo_dane' => '15806'],
            ['name' => 'TINJACÁ', 'codigo_dane' => '15808'],
            ['name' => 'TIPACOQUE', 'codigo_dane' => '15810'],
            ['name' => 'TOCA', 'codigo_dane' => '15814'],
            ['name' => 'TOGÜÍ', 'codigo_dane' => '15816'],
            ['name' => 'TÓPAGA', 'codigo_dane' => '15820'],
            ['name' => 'TOTA', 'codigo_dane' => '15822'],
            ['name' => 'TUNUNGUÁ', 'codigo_dane' => '15832'],
            ['name' => 'TURMEQUÉ', 'codigo_dane' => '15835'],
            ['name' => 'TUTA', 'codigo_dane' => '15837'],
            ['name' => 'TUTAZÁ', 'codigo_dane' => '15839'],
            ['name' => 'ÚMBITA', 'codigo_dane' => '15842'],
            ['name' => 'VENTAQUEMADA', 'codigo_dane' => '15861'],
            ['name' => 'VIRACACHÁ', 'codigo_dane' => '15879'],
            ['name' => 'ZETAQUIRA', 'codigo_dane' => '15897'],
            ['name' => 'MANIZALES', 'codigo_dane' => '17001'],
            ['name' => 'AGUADAS', 'codigo_dane' => '17013'],
            ['name' => 'ANSERMA', 'codigo_dane' => '17042'],
            ['name' => 'ARANZAZU', 'codigo_dane' => '17050'],
            ['name' => 'BELALCÁZAR', 'codigo_dane' => '17088'],
            ['name' => 'CHINCHINÁ', 'codigo_dane' => '17174'],
            ['name' => 'FILADELFIA', 'codigo_dane' => '17272'],
            ['name' => 'LA DORADA', 'codigo_dane' => '17380'],
            ['name' => 'LA MERCED', 'codigo_dane' => '17388'],
            ['name' => 'MANZANARES', 'codigo_dane' => '17433'],
            ['name' => 'MARMATO', 'codigo_dane' => '17442'],
            ['name' => 'MARQUETALIA', 'codigo_dane' => '17444'],
            ['name' => 'MARULANDA', 'codigo_dane' => '17446'],
            ['name' => 'NEIRA', 'codigo_dane' => '17486'],
            ['name' => 'NORCASIA', 'codigo_dane' => '17495'],
            ['name' => 'PÁCORA', 'codigo_dane' => '17513'],
            ['name' => 'PALESTINA', 'codigo_dane' => '17524'],
            ['name' => 'PENSILVANIA', 'codigo_dane' => '17541'],
            ['name' => 'RIOSUCIO', 'codigo_dane' => '17614'],
            ['name' => 'RISARALDA', 'codigo_dane' => '17616'],
            ['name' => 'SALAMINA', 'codigo_dane' => '17653'],
            ['name' => 'SAMANÁ', 'codigo_dane' => '17662'],
            ['name' => 'SAN JOSÉ', 'codigo_dane' => '17665'],
            ['name' => 'SUPÍA', 'codigo_dane' => '17777'],
            ['name' => 'VICTORIA', 'codigo_dane' => '17867'],
            ['name' => 'VILLAMARÍA', 'codigo_dane' => '17873'],
            ['name' => 'VITERBO', 'codigo_dane' => '17877'],
            ['name' => 'FLORENCIA', 'codigo_dane' => '18001'],
            ['name' => 'ALBANIA', 'codigo_dane' => '18029'],
            ['name' => 'BELÉN DE LOS ANDAQUÍES', 'codigo_dane' => '18094'],
            ['name' => 'CARTAGENA DEL CHAIRÁ', 'codigo_dane' => '18150'],
            ['name' => 'CURILLO', 'codigo_dane' => '18205'],
            ['name' => 'EL DONCELLO', 'codigo_dane' => '18247'],
            ['name' => 'EL PAUJÍL', 'codigo_dane' => '18256'],
            ['name' => 'LA MONTAÑITA', 'codigo_dane' => '18410'],
            ['name' => 'MILÁN', 'codigo_dane' => '18460'],
            ['name' => 'MORELIA', 'codigo_dane' => '18479'],
            ['name' => 'PUERTO RICO', 'codigo_dane' => '18592'],
            ['name' => 'SAN JOSÉ DEL FRAGUA', 'codigo_dane' => '18610'],
            ['name' => 'SAN VICENTE DEL CAGUÁN', 'codigo_dane' => '18753'],
            ['name' => 'SOLANO', 'codigo_dane' => '18756'],
            ['name' => 'SOLITA', 'codigo_dane' => '18785'],
            ['name' => 'VALPARAÍSO', 'codigo_dane' => '18860'],
            ['name' => 'POPAYÁN', 'codigo_dane' => '19001'],
            ['name' => 'ALMAGUER', 'codigo_dane' => '19022'],
            ['name' => 'ARGELIA', 'codigo_dane' => '19050'],
            ['name' => 'BALBOA', 'codigo_dane' => '19075'],
            ['name' => 'BOLÍVAR', 'codigo_dane' => '19100'],
            ['name' => 'BUENOS AIRES', 'codigo_dane' => '19110'],
            ['name' => 'CAJIBÍO', 'codigo_dane' => '19130'],
            ['name' => 'CALDONO', 'codigo_dane' => '19137'],
            ['name' => 'CALOTO', 'codigo_dane' => '19142'],
            ['name' => 'CORINTO', 'codigo_dane' => '19212'],
            ['name' => 'EL TAMBO', 'codigo_dane' => '19256'],
            ['name' => 'FLORENCIA', 'codigo_dane' => '19290'],
            ['name' => 'GUACHENÉ', 'codigo_dane' => '19300'],
            ['name' => 'GUAPI', 'codigo_dane' => '19318'],
            ['name' => 'INZÁ', 'codigo_dane' => '19355'],
            ['name' => 'JAMBALÓ', 'codigo_dane' => '19364'],
            ['name' => 'LA SIERRA', 'codigo_dane' => '19392'],
            ['name' => 'LA VEGA', 'codigo_dane' => '19397'],
            ['name' => 'LÓPEZ DE MICAY', 'codigo_dane' => '19418'],
            ['name' => 'MERCADERES', 'codigo_dane' => '19450'],
            ['name' => 'MIRANDA', 'codigo_dane' => '19455'],
            ['name' => 'MORALES', 'codigo_dane' => '19473'],
            ['name' => 'PADILLA', 'codigo_dane' => '19513'],
            ['name' => 'PÁEZ', 'codigo_dane' => '19517'],
            ['name' => 'PATÍA', 'codigo_dane' => '19532'],
            ['name' => 'PIAMONTE', 'codigo_dane' => '19533'],
            ['name' => 'PIENDAMÓ - TUNÍA', 'codigo_dane' => '19548'],
            ['name' => 'PUERTO TEJADA', 'codigo_dane' => '19573'],
            ['name' => 'PURACÉ', 'codigo_dane' => '19585'],
            ['name' => 'ROSAS', 'codigo_dane' => '19622'],
            ['name' => 'SAN SEBASTIÁN', 'codigo_dane' => '19693'],
            ['name' => 'SANTANDER DE QUILICHAO', 'codigo_dane' => '19698'],
            ['name' => 'SANTA ROSA', 'codigo_dane' => '19701'],
            ['name' => 'SILVIA', 'codigo_dane' => '19743'],
            ['name' => 'SOTARÁ - PAISPAMBA', 'codigo_dane' => '19760'],
            ['name' => 'SUÁREZ', 'codigo_dane' => '19780'],
            ['name' => 'SUCRE', 'codigo_dane' => '19785'],
            ['name' => 'TIMBÍO', 'codigo_dane' => '19807'],
            ['name' => 'TIMBIQUÍ', 'codigo_dane' => '19809'],
            ['name' => 'TORIBÍO', 'codigo_dane' => '19821'],
            ['name' => 'TOTORÓ', 'codigo_dane' => '19824'],
            ['name' => 'VILLA RICA', 'codigo_dane' => '19845'],
            ['name' => 'VALLEDUPAR', 'codigo_dane' => '20001'],
            ['name' => 'AGUACHICA', 'codigo_dane' => '20011'],
            ['name' => 'AGUSTÍN CODAZZI', 'codigo_dane' => '20013'],
            ['name' => 'ASTREA', 'codigo_dane' => '20032'],
            ['name' => 'BECERRIL', 'codigo_dane' => '20045'],
            ['name' => 'BOSCONIA', 'codigo_dane' => '20060'],
            ['name' => 'CHIMICHAGUA', 'codigo_dane' => '20175'],
            ['name' => 'CHIRIGUANÁ', 'codigo_dane' => '20178'],
            ['name' => 'CURUMANÍ', 'codigo_dane' => '20228'],
            ['name' => 'EL COPEY', 'codigo_dane' => '20238'],
            ['name' => 'EL PASO', 'codigo_dane' => '20250'],
            ['name' => 'GAMARRA', 'codigo_dane' => '20295'],
            ['name' => 'GONZÁLEZ', 'codigo_dane' => '20310'],
            ['name' => 'LA GLORIA', 'codigo_dane' => '20383'],
            ['name' => 'LA JAGUA DE IBIRICO', 'codigo_dane' => '20400'],
            ['name' => 'MANAURE BALCÓN DEL CESAR', 'codigo_dane' => '20443'],
            ['name' => 'PAILITAS', 'codigo_dane' => '20517'],
            ['name' => 'PELAYA', 'codigo_dane' => '20550'],
            ['name' => 'PUEBLO BELLO', 'codigo_dane' => '20570'],
            ['name' => 'RÍO DE ORO', 'codigo_dane' => '20614'],
            ['name' => 'LA PAZ', 'codigo_dane' => '20621'],
            ['name' => 'SAN ALBERTO', 'codigo_dane' => '20710'],
            ['name' => 'SAN DIEGO', 'codigo_dane' => '20750'],
            ['name' => 'SAN MARTÍN', 'codigo_dane' => '20770'],
            ['name' => 'TAMALAMEQUE', 'codigo_dane' => '20787'],
            ['name' => 'MONTERÍA', 'codigo_dane' => '23001'],
            ['name' => 'AYAPEL', 'codigo_dane' => '23068'],
            ['name' => 'BUENAVISTA', 'codigo_dane' => '23079'],
            ['name' => 'CANALETE', 'codigo_dane' => '23090'],
            ['name' => 'CERETÉ', 'codigo_dane' => '23162'],
            ['name' => 'CHIMÁ', 'codigo_dane' => '23168'],
            ['name' => 'CHINÚ', 'codigo_dane' => '23182'],
            ['name' => 'CIÉNAGA DE ORO', 'codigo_dane' => '23189'],
            ['name' => 'COTORRA', 'codigo_dane' => '23300'],
            ['name' => 'LA APARTADA', 'codigo_dane' => '23350'],
            ['name' => 'LORICA', 'codigo_dane' => '23417'],
            ['name' => 'LOS CÓRDOBAS', 'codigo_dane' => '23419'],
            ['name' => 'MOMIL', 'codigo_dane' => '23464'],
            ['name' => 'MONTELÍBANO', 'codigo_dane' => '23466'],
            ['name' => 'MOÑITOS', 'codigo_dane' => '23500'],
            ['name' => 'PLANETA RICA', 'codigo_dane' => '23555'],
            ['name' => 'PUEBLO NUEVO', 'codigo_dane' => '23570'],
            ['name' => 'PUERTO ESCONDIDO', 'codigo_dane' => '23574'],
            ['name' => 'PUERTO LIBERTADOR', 'codigo_dane' => '23580'],
            ['name' => 'PURÍSIMA DE LA CONCEPCIÓN', 'codigo_dane' => '23586'],
            ['name' => 'SAHAGÚN', 'codigo_dane' => '23660'],
            ['name' => 'SAN ANDRÉS DE SOTAVENTO', 'codigo_dane' => '23670'],
            ['name' => 'SAN ANTERO', 'codigo_dane' => '23672'],
            ['name' => 'SAN BERNARDO DEL VIENTO', 'codigo_dane' => '23675'],
            ['name' => 'SAN CARLOS', 'codigo_dane' => '23678'],
            ['name' => 'SAN JOSÉ DE URÉ', 'codigo_dane' => '23682'],
            ['name' => 'SAN PELAYO', 'codigo_dane' => '23686'],
            ['name' => 'TIERRALTA', 'codigo_dane' => '23807'],
            ['name' => 'TUCHÍN', 'codigo_dane' => '23815'],
            ['name' => 'VALENCIA', 'codigo_dane' => '23855'],
            ['name' => 'AGUA DE DIOS', 'codigo_dane' => '25001'],
            ['name' => 'ALBÁN', 'codigo_dane' => '25019'],
            ['name' => 'ANAPOIMA', 'codigo_dane' => '25035'],
            ['name' => 'ANOLAIMA', 'codigo_dane' => '25040'],
            ['name' => 'ARBELÁEZ', 'codigo_dane' => '25053'],
            ['name' => 'BELTRÁN', 'codigo_dane' => '25086'],
            ['name' => 'BITUIMA', 'codigo_dane' => '25095'],
            ['name' => 'BOJACÁ', 'codigo_dane' => '25099'],
            ['name' => 'CABRERA', 'codigo_dane' => '25120'],
            ['name' => 'CACHIPAY', 'codigo_dane' => '25123'],
            ['name' => 'CAJICÁ', 'codigo_dane' => '25126'],
            ['name' => 'CAPARRAPÍ', 'codigo_dane' => '25148'],
            ['name' => 'CÁQUEZA', 'codigo_dane' => '25151'],
            ['name' => 'CARMEN DE CARUPA', 'codigo_dane' => '25154'],
            ['name' => 'CHAGUANÍ', 'codigo_dane' => '25168'],
            ['name' => 'CHÍA', 'codigo_dane' => '25175'],
            ['name' => 'CHIPAQUE', 'codigo_dane' => '25178'],
            ['name' => 'CHOACHÍ', 'codigo_dane' => '25181'],
            ['name' => 'CHOCONTÁ', 'codigo_dane' => '25183'],
            ['name' => 'COGUA', 'codigo_dane' => '25200'],
            ['name' => 'COTA', 'codigo_dane' => '25214'],
            ['name' => 'CUCUNUBÁ', 'codigo_dane' => '25224'],
            ['name' => 'EL COLEGIO', 'codigo_dane' => '25245'],
            ['name' => 'EL PEÑÓN', 'codigo_dane' => '25258'],
            ['name' => 'EL ROSAL', 'codigo_dane' => '25260'],
            ['name' => 'FACATATIVÁ', 'codigo_dane' => '25269'],
            ['name' => 'FÓMEQUE', 'codigo_dane' => '25279'],
            ['name' => 'FOSCA', 'codigo_dane' => '25281'],
            ['name' => 'FUNZA', 'codigo_dane' => '25286'],
            ['name' => 'FÚQUENE', 'codigo_dane' => '25288'],
            ['name' => 'FUSAGASUGÁ', 'codigo_dane' => '25290'],
            ['name' => 'GACHALÁ', 'codigo_dane' => '25293'],
            ['name' => 'GACHANCIPÁ', 'codigo_dane' => '25295'],
            ['name' => 'GACHETÁ', 'codigo_dane' => '25297'],
            ['name' => 'GAMA', 'codigo_dane' => '25299'],
            ['name' => 'GIRARDOT', 'codigo_dane' => '25307'],
            ['name' => 'GRANADA', 'codigo_dane' => '25312'],
            ['name' => 'GUACHETÁ', 'codigo_dane' => '25317'],
            ['name' => 'GUADUAS', 'codigo_dane' => '25320'],
            ['name' => 'GUASCA', 'codigo_dane' => '25322'],
            ['name' => 'GUATAQUÍ', 'codigo_dane' => '25324'],
            ['name' => 'GUATAVITA', 'codigo_dane' => '25326'],
            ['name' => 'GUAYABAL DE SÍQUIMA', 'codigo_dane' => '25328'],
            ['name' => 'GUAYABETAL', 'codigo_dane' => '25335'],
            ['name' => 'GUTIÉRREZ', 'codigo_dane' => '25339'],
            ['name' => 'JERUSALÉN', 'codigo_dane' => '25368'],
            ['name' => 'JUNÍN', 'codigo_dane' => '25372'],
            ['name' => 'LA CALERA', 'codigo_dane' => '25377'],
            ['name' => 'LA MESA', 'codigo_dane' => '25386'],
            ['name' => 'LA PALMA', 'codigo_dane' => '25394'],
            ['name' => 'LA PEÑA', 'codigo_dane' => '25398'],
            ['name' => 'LA VEGA', 'codigo_dane' => '25402'],
            ['name' => 'LENGUAZAQUE', 'codigo_dane' => '25407'],
            ['name' => 'MACHETÁ', 'codigo_dane' => '25426'],
            ['name' => 'MADRID', 'codigo_dane' => '25430'],
            ['name' => 'MANTA', 'codigo_dane' => '25436'],
            ['name' => 'MEDINA', 'codigo_dane' => '25438'],
            ['name' => 'MOSQUERA', 'codigo_dane' => '25473'],
            ['name' => 'NARIÑO', 'codigo_dane' => '25483'],
            ['name' => 'NEMOCÓN', 'codigo_dane' => '25486'],
            ['name' => 'NILO', 'codigo_dane' => '25488'],
            ['name' => 'NIMAIMA', 'codigo_dane' => '25489'],
            ['name' => 'NOCAIMA', 'codigo_dane' => '25491'],
            ['name' => 'VENECIA', 'codigo_dane' => '25506'],
            ['name' => 'PACHO', 'codigo_dane' => '25513'],
            ['name' => 'PAIME', 'codigo_dane' => '25518'],
            ['name' => 'PANDI', 'codigo_dane' => '25524'],
            ['name' => 'PARATEBUENO', 'codigo_dane' => '25530'],
            ['name' => 'PASCA', 'codigo_dane' => '25535'],
            ['name' => 'PUERTO SALGAR', 'codigo_dane' => '25572'],
            ['name' => 'PULÍ', 'codigo_dane' => '25580'],
            ['name' => 'QUEBRADANEGRA', 'codigo_dane' => '25592'],
            ['name' => 'QUETAME', 'codigo_dane' => '25594'],
            ['name' => 'QUIPILE', 'codigo_dane' => '25596'],
            ['name' => 'APULO', 'codigo_dane' => '25599'],
            ['name' => 'RICAURTE', 'codigo_dane' => '25612'],
            ['name' => 'SAN ANTONIO DEL TEQUENDAMA', 'codigo_dane' => '25645'],
            ['name' => 'SAN BERNARDO', 'codigo_dane' => '25649'],
            ['name' => 'SAN CAYETANO', 'codigo_dane' => '25653'],
            ['name' => 'SAN FRANCISCO', 'codigo_dane' => '25658'],
            ['name' => 'SAN JUAN DE RIOSECO', 'codigo_dane' => '25662'],
            ['name' => 'SASAIMA', 'codigo_dane' => '25718'],
            ['name' => 'SESQUILÉ', 'codigo_dane' => '25736'],
            ['name' => 'SIBATÉ', 'codigo_dane' => '25740'],
            ['name' => 'SILVANIA', 'codigo_dane' => '25743'],
            ['name' => 'SIMIJACA', 'codigo_dane' => '25745'],
            ['name' => 'SOACHA', 'codigo_dane' => '25754'],
            ['name' => 'SOPÓ', 'codigo_dane' => '25758'],
            ['name' => 'SUBACHOQUE', 'codigo_dane' => '25769'],
            ['name' => 'SUESCA', 'codigo_dane' => '25772'],
            ['name' => 'SUPATÁ', 'codigo_dane' => '25777'],
            ['name' => 'SUSA', 'codigo_dane' => '25779'],
            ['name' => 'SUTATAUSA', 'codigo_dane' => '25781'],
            ['name' => 'TABIO', 'codigo_dane' => '25785'],
            ['name' => 'TAUSA', 'codigo_dane' => '25793'],
            ['name' => 'TENA', 'codigo_dane' => '25797'],
            ['name' => 'TENJO', 'codigo_dane' => '25799'],
            ['name' => 'TIBACUY', 'codigo_dane' => '25805'],
            ['name' => 'TIBIRITA', 'codigo_dane' => '25807'],
            ['name' => 'TOCAIMA', 'codigo_dane' => '25815'],
            ['name' => 'TOCANCIPÁ', 'codigo_dane' => '25817'],
            ['name' => 'TOPAIPÍ', 'codigo_dane' => '25823'],
            ['name' => 'UBALÁ', 'codigo_dane' => '25839'],
            ['name' => 'UBAQUE', 'codigo_dane' => '25841'],
            ['name' => 'VILLA DE SAN DIEGO DE UBATÉ', 'codigo_dane' => '25843'],
            ['name' => 'UNE', 'codigo_dane' => '25845'],
            ['name' => 'ÚTICA', 'codigo_dane' => '25851'],
            ['name' => 'VERGARA', 'codigo_dane' => '25862'],
            ['name' => 'VIANÍ', 'codigo_dane' => '25867'],
            ['name' => 'VILLAGÓMEZ', 'codigo_dane' => '25871'],
            ['name' => 'VILLAPINZÓN', 'codigo_dane' => '25873'],
            ['name' => 'VILLETA', 'codigo_dane' => '25875'],
            ['name' => 'VIOTÁ', 'codigo_dane' => '25878'],
            ['name' => 'YACOPÍ', 'codigo_dane' => '25885'],
            ['name' => 'ZIPACÓN', 'codigo_dane' => '25898'],
            ['name' => 'ZIPAQUIRÁ', 'codigo_dane' => '25899'],
            ['name' => 'QUIBDÓ', 'codigo_dane' => '27001'],
            ['name' => 'ACANDÍ', 'codigo_dane' => '27006'],
            ['name' => 'ALTO BAUDÓ', 'codigo_dane' => '27025'],
            ['name' => 'ATRATO', 'codigo_dane' => '27050'],
            ['name' => 'BAGADÓ', 'codigo_dane' => '27073'],
            ['name' => 'BAHÍA SOLANO', 'codigo_dane' => '27075'],
            ['name' => 'BAJO BAUDÓ', 'codigo_dane' => '27077'],
            ['name' => 'BOJAYÁ', 'codigo_dane' => '27099'],
            ['name' => 'EL CANTÓN DEL SAN PABLO', 'codigo_dane' => '27135'],
            ['name' => 'CARMEN DEL DARIÉN', 'codigo_dane' => '27150'],
            ['name' => 'CÉRTEGUI', 'codigo_dane' => '27160'],
            ['name' => 'CONDOTO', 'codigo_dane' => '27205'],
            ['name' => 'EL CARMEN DE ATRATO', 'codigo_dane' => '27245'],
            ['name' => 'EL LITORAL DEL SAN JUAN', 'codigo_dane' => '27250'],
            ['name' => 'ISTMINA', 'codigo_dane' => '27361'],
            ['name' => 'JURADÓ', 'codigo_dane' => '27372'],
            ['name' => 'LLORÓ', 'codigo_dane' => '27413'],
            ['name' => 'MEDIO ATRATO', 'codigo_dane' => '27425'],
            ['name' => 'MEDIO BAUDÓ', 'codigo_dane' => '27430'],
            ['name' => 'MEDIO SAN JUAN', 'codigo_dane' => '27450'],
            ['name' => 'NÓVITA', 'codigo_dane' => '27491'],
            ['name' => 'NUEVO BELÉN DE BAJIRÁ', 'codigo_dane' => '27493'],
            ['name' => 'NUQUÍ', 'codigo_dane' => '27495'],
            ['name' => 'RÍO IRÓ', 'codigo_dane' => '27580'],
            ['name' => 'RÍO QUITO', 'codigo_dane' => '27600'],
            ['name' => 'RIOSUCIO', 'codigo_dane' => '27615'],
            ['name' => 'SAN JOSÉ DEL PALMAR', 'codigo_dane' => '27660'],
            ['name' => 'SIPÍ', 'codigo_dane' => '27745'],
            ['name' => 'TADÓ', 'codigo_dane' => '27787'],
            ['name' => 'UNGUÍA', 'codigo_dane' => '27800'],
            ['name' => 'UNIÓN PANAMERICANA', 'codigo_dane' => '27810'],
            ['name' => 'NEIVA', 'codigo_dane' => '41001'],
            ['name' => 'ACEVEDO', 'codigo_dane' => '41006'],
            ['name' => 'AGRADO', 'codigo_dane' => '41013'],
            ['name' => 'AIPE', 'codigo_dane' => '41016'],
            ['name' => 'ALGECIRAS', 'codigo_dane' => '41020'],
            ['name' => 'ALTAMIRA', 'codigo_dane' => '41026'],
            ['name' => 'BARAYA', 'codigo_dane' => '41078'],
            ['name' => 'CAMPOALEGRE', 'codigo_dane' => '41132'],
            ['name' => 'COLOMBIA', 'codigo_dane' => '41206'],
            ['name' => 'ELÍAS', 'codigo_dane' => '41244'],
            ['name' => 'GARZÓN', 'codigo_dane' => '41298'],
            ['name' => 'GIGANTE', 'codigo_dane' => '41306'],
            ['name' => 'GUADALUPE', 'codigo_dane' => '41319'],
            ['name' => 'HOBO', 'codigo_dane' => '41349'],
            ['name' => 'ÍQUIRA', 'codigo_dane' => '41357'],
            ['name' => 'ISNOS', 'codigo_dane' => '41359'],
            ['name' => 'LA ARGENTINA', 'codigo_dane' => '41378'],
            ['name' => 'LA PLATA', 'codigo_dane' => '41396'],
            ['name' => 'NÁTAGA', 'codigo_dane' => '41483'],
            ['name' => 'OPORAPA', 'codigo_dane' => '41503'],
            ['name' => 'PAICOL', 'codigo_dane' => '41518'],
            ['name' => 'PALERMO', 'codigo_dane' => '41524'],
            ['name' => 'PALESTINA', 'codigo_dane' => '41530'],
            ['name' => 'PITAL', 'codigo_dane' => '41548'],
            ['name' => 'PITALITO', 'codigo_dane' => '41551'],
            ['name' => 'RIVERA', 'codigo_dane' => '41615'],
            ['name' => 'SALADOBLANCO', 'codigo_dane' => '41660'],
            ['name' => 'SAN AGUSTÍN', 'codigo_dane' => '41668'],
            ['name' => 'SANTA MARÍA', 'codigo_dane' => '41676'],
            ['name' => 'SUAZA', 'codigo_dane' => '41770'],
            ['name' => 'TARQUI', 'codigo_dane' => '41791'],
            ['name' => 'TESALIA', 'codigo_dane' => '41797'],
            ['name' => 'TELLO', 'codigo_dane' => '41799'],
            ['name' => 'TERUEL', 'codigo_dane' => '41801'],
            ['name' => 'TIMANÁ', 'codigo_dane' => '41807'],
            ['name' => 'VILLAVIEJA', 'codigo_dane' => '41872'],
            ['name' => 'YAGUARÁ', 'codigo_dane' => '41885'],
            ['name' => 'RIOHACHA', 'codigo_dane' => '44001'],
            ['name' => 'ALBANIA', 'codigo_dane' => '44035'],
            ['name' => 'BARRANCAS', 'codigo_dane' => '44078'],
            ['name' => 'DIBULLA', 'codigo_dane' => '44090'],
            ['name' => 'DISTRACCIÓN', 'codigo_dane' => '44098'],
            ['name' => 'EL MOLINO', 'codigo_dane' => '44110'],
            ['name' => 'FONSECA', 'codigo_dane' => '44279'],
            ['name' => 'HATONUEVO', 'codigo_dane' => '44378'],
            ['name' => 'LA JAGUA DEL PILAR', 'codigo_dane' => '44420'],
            ['name' => 'MAICAO', 'codigo_dane' => '44430'],
            ['name' => 'MANAURE', 'codigo_dane' => '44560'],
            ['name' => 'SAN JUAN DEL CESAR', 'codigo_dane' => '44650'],
            ['name' => 'URIBIA', 'codigo_dane' => '44847'],
            ['name' => 'URUMITA', 'codigo_dane' => '44855'],
            ['name' => 'VILLANUEVA', 'codigo_dane' => '44874'],
            ['name' => 'SANTA MARTA', 'codigo_dane' => '47001'],
            ['name' => 'ALGARROBO', 'codigo_dane' => '47030'],
            ['name' => 'ARACATACA', 'codigo_dane' => '47053'],
            ['name' => 'ARIGUANÍ', 'codigo_dane' => '47058'],
            ['name' => 'CERRO DE SAN ANTONIO', 'codigo_dane' => '47161'],
            ['name' => 'CHIVOLO', 'codigo_dane' => '47170'],
            ['name' => 'CIÉNAGA', 'codigo_dane' => '47189'],
            ['name' => 'CONCORDIA', 'codigo_dane' => '47205'],
            ['name' => 'EL BANCO', 'codigo_dane' => '47245'],
            ['name' => 'EL PIÑÓN', 'codigo_dane' => '47258'],
            ['name' => 'EL RETÉN', 'codigo_dane' => '47268'],
            ['name' => 'FUNDACIÓN', 'codigo_dane' => '47288'],
            ['name' => 'GUAMAL', 'codigo_dane' => '47318'],
            ['name' => 'NUEVA GRANADA', 'codigo_dane' => '47460'],
            ['name' => 'PEDRAZA', 'codigo_dane' => '47541'],
            ['name' => 'PIJIÑO DEL CARMEN', 'codigo_dane' => '47545'],
            ['name' => 'PIVIJAY', 'codigo_dane' => '47551'],
            ['name' => 'PLATO', 'codigo_dane' => '47555'],
            ['name' => 'PUEBLOVIEJO', 'codigo_dane' => '47570'],
            ['name' => 'REMOLINO', 'codigo_dane' => '47605'],
            ['name' => 'SABANAS DE SAN ÁNGEL', 'codigo_dane' => '47660'],
            ['name' => 'SALAMINA', 'codigo_dane' => '47675'],
            ['name' => 'SAN SEBASTIÁN DE BUENAVISTA', 'codigo_dane' => '47692'],
            ['name' => 'SAN ZENÓN', 'codigo_dane' => '47703'],
            ['name' => 'SANTA ANA', 'codigo_dane' => '47707'],
            ['name' => 'SANTA BÁRBARA DE PINTO', 'codigo_dane' => '47720'],
            ['name' => 'SITIONUEVO', 'codigo_dane' => '47745'],
            ['name' => 'TENERIFE', 'codigo_dane' => '47798'],
            ['name' => 'ZAPAYÁN', 'codigo_dane' => '47960'],
            ['name' => 'ZONA BANANERA', 'codigo_dane' => '47980'],
            ['name' => 'VILLAVICENCIO', 'codigo_dane' => '50001'],
            ['name' => 'ACACÍAS', 'codigo_dane' => '50006'],
            ['name' => 'BARRANCA DE UPÍA', 'codigo_dane' => '50110'],
            ['name' => 'CABUYARO', 'codigo_dane' => '50124'],
            ['name' => 'CASTILLA LA NUEVA', 'codigo_dane' => '50150'],
            ['name' => 'CUBARRAL', 'codigo_dane' => '50223'],
            ['name' => 'CUMARAL', 'codigo_dane' => '50226'],
            ['name' => 'EL CALVARIO', 'codigo_dane' => '50245'],
            ['name' => 'EL CASTILLO', 'codigo_dane' => '50251'],
            ['name' => 'EL DORADO', 'codigo_dane' => '50270'],
            ['name' => 'FUENTE DE ORO', 'codigo_dane' => '50287'],
            ['name' => 'GRANADA', 'codigo_dane' => '50313'],
            ['name' => 'GUAMAL', 'codigo_dane' => '50318'],
            ['name' => 'MAPIRIPÁN', 'codigo_dane' => '50325'],
            ['name' => 'MESETAS', 'codigo_dane' => '50330'],
            ['name' => 'LA MACARENA', 'codigo_dane' => '50350'],
            ['name' => 'URIBE', 'codigo_dane' => '50370'],
            ['name' => 'LEJANÍAS', 'codigo_dane' => '50400'],
            ['name' => 'PUERTO CONCORDIA', 'codigo_dane' => '50450'],
            ['name' => 'PUERTO GAITÁN', 'codigo_dane' => '50568'],
            ['name' => 'PUERTO LÓPEZ', 'codigo_dane' => '50573'],
            ['name' => 'PUERTO LLERAS', 'codigo_dane' => '50577'],
            ['name' => 'PUERTO RICO', 'codigo_dane' => '50590'],
            ['name' => 'RESTREPO', 'codigo_dane' => '50606'],
            ['name' => 'SAN CARLOS DE GUAROA', 'codigo_dane' => '50680'],
            ['name' => 'SAN JUAN DE ARAMA', 'codigo_dane' => '50683'],
            ['name' => 'SAN JUANITO', 'codigo_dane' => '50686'],
            ['name' => 'SAN MARTÍN', 'codigo_dane' => '50689'],
            ['name' => 'VISTAHERMOSA', 'codigo_dane' => '50711'],
            ['name' => 'PASTO', 'codigo_dane' => '52001'],
            ['name' => 'ALBÁN', 'codigo_dane' => '52019'],
            ['name' => 'ALDANA', 'codigo_dane' => '52022'],
            ['name' => 'ANCUYA', 'codigo_dane' => '52036'],
            ['name' => 'ARBOLEDA', 'codigo_dane' => '52051'],
            ['name' => 'BARBACOAS', 'codigo_dane' => '52079'],
            ['name' => 'BELÉN', 'codigo_dane' => '52083'],
            ['name' => 'BUESACO', 'codigo_dane' => '52110'],
            ['name' => 'COLÓN', 'codigo_dane' => '52203'],
            ['name' => 'CONSACÁ', 'codigo_dane' => '52207'],
            ['name' => 'CONTADERO', 'codigo_dane' => '52210'],
            ['name' => 'CÓRDOBA', 'codigo_dane' => '52215'],
            ['name' => 'CUASPUD CARLOSAMA', 'codigo_dane' => '52224'],
            ['name' => 'CUMBAL', 'codigo_dane' => '52227'],
            ['name' => 'CUMBITARA', 'codigo_dane' => '52233'],
            ['name' => 'CHACHAGÜÍ', 'codigo_dane' => '52240'],
            ['name' => 'EL CHARCO', 'codigo_dane' => '52250'],
            ['name' => 'EL PEÑOL', 'codigo_dane' => '52254'],
            ['name' => 'EL ROSARIO', 'codigo_dane' => '52256'],
            ['name' => 'EL TABLÓN DE GÓMEZ', 'codigo_dane' => '52258'],
            ['name' => 'EL TAMBO', 'codigo_dane' => '52260'],
            ['name' => 'FUNES', 'codigo_dane' => '52287'],
            ['name' => 'GUACHUCAL', 'codigo_dane' => '52317'],
            ['name' => 'GUAITARILLA', 'codigo_dane' => '52320'],
            ['name' => 'GUALMATÁN', 'codigo_dane' => '52323'],
            ['name' => 'ILES', 'codigo_dane' => '52352'],
            ['name' => 'IMUÉS', 'codigo_dane' => '52354'],
            ['name' => 'IPIALES', 'codigo_dane' => '52356'],
            ['name' => 'LA CRUZ', 'codigo_dane' => '52378'],
            ['name' => 'LA FLORIDA', 'codigo_dane' => '52381'],
            ['name' => 'LA LLANADA', 'codigo_dane' => '52385'],
            ['name' => 'LA TOLA', 'codigo_dane' => '52390'],
            ['name' => 'LA UNIÓN', 'codigo_dane' => '52399'],
            ['name' => 'LEIVA', 'codigo_dane' => '52405'],
            ['name' => 'LINARES', 'codigo_dane' => '52411'],
            ['name' => 'LOS ANDES', 'codigo_dane' => '52418'],
            ['name' => 'MAGÜÍ', 'codigo_dane' => '52427'],
            ['name' => 'MALLAMA', 'codigo_dane' => '52435'],
            ['name' => 'MOSQUERA', 'codigo_dane' => '52473'],
            ['name' => 'NARIÑO', 'codigo_dane' => '52480'],
            ['name' => 'OLAYA HERRERA', 'codigo_dane' => '52490'],
            ['name' => 'OSPINA', 'codigo_dane' => '52506'],
            ['name' => 'FRANCISCO PIZARRO', 'codigo_dane' => '52520'],
            ['name' => 'POLICARPA', 'codigo_dane' => '52540'],
            ['name' => 'POTOSÍ', 'codigo_dane' => '52560'],
            ['name' => 'PROVIDENCIA', 'codigo_dane' => '52565'],
            ['name' => 'PUERRES', 'codigo_dane' => '52573'],
            ['name' => 'PUPIALES', 'codigo_dane' => '52585'],
            ['name' => 'RICAURTE', 'codigo_dane' => '52612'],
            ['name' => 'ROBERTO PAYÁN', 'codigo_dane' => '52621'],
            ['name' => 'SAMANIEGO', 'codigo_dane' => '52678'],
            ['name' => 'SANDONÁ', 'codigo_dane' => '52683'],
            ['name' => 'SAN BERNARDO', 'codigo_dane' => '52685'],
            ['name' => 'SAN LORENZO', 'codigo_dane' => '52687'],
            ['name' => 'SAN PABLO', 'codigo_dane' => '52693'],
            ['name' => 'SAN PEDRO DE CARTAGO', 'codigo_dane' => '52694'],
            ['name' => 'SANTA BÁRBARA', 'codigo_dane' => '52696'],
            ['name' => 'SANTACRUZ', 'codigo_dane' => '52699'],
            ['name' => 'SAPUYES', 'codigo_dane' => '52720'],
            ['name' => 'TAMINANGO', 'codigo_dane' => '52786'],
            ['name' => 'TANGUA', 'codigo_dane' => '52788'],
            ['name' => 'SAN ANDRÉS DE TUMACO', 'codigo_dane' => '52835'],
            ['name' => 'TÚQUERRES', 'codigo_dane' => '52838'],
            ['name' => 'YACUANQUER', 'codigo_dane' => '52885'],
            ['name' => 'SAN JOSÉ DE CÚCUTA', 'codigo_dane' => '54001'],
            ['name' => 'ÁBREGO', 'codigo_dane' => '54003'],
            ['name' => 'ARBOLEDAS', 'codigo_dane' => '54051'],
            ['name' => 'BOCHALEMA', 'codigo_dane' => '54099'],
            ['name' => 'BUCARASICA', 'codigo_dane' => '54109'],
            ['name' => 'CÁCOTA', 'codigo_dane' => '54125'],
            ['name' => 'CÁCHIRA', 'codigo_dane' => '54128'],
            ['name' => 'CHINÁCOTA', 'codigo_dane' => '54172'],
            ['name' => 'CHITAGÁ', 'codigo_dane' => '54174'],
            ['name' => 'CONVENCIÓN', 'codigo_dane' => '54206'],
            ['name' => 'CUCUTILLA', 'codigo_dane' => '54223'],
            ['name' => 'DURANIA', 'codigo_dane' => '54239'],
            ['name' => 'EL CARMEN', 'codigo_dane' => '54245'],
            ['name' => 'EL TARRA', 'codigo_dane' => '54250'],
            ['name' => 'EL ZULIA', 'codigo_dane' => '54261'],
            ['name' => 'GRAMALOTE', 'codigo_dane' => '54313'],
            ['name' => 'HACARÍ', 'codigo_dane' => '54344'],
            ['name' => 'HERRÁN', 'codigo_dane' => '54347'],
            ['name' => 'LABATECA', 'codigo_dane' => '54377'],
            ['name' => 'LA ESPERANZA', 'codigo_dane' => '54385'],
            ['name' => 'LA PLAYA', 'codigo_dane' => '54398'],
            ['name' => 'LOS PATIOS', 'codigo_dane' => '54405'],
            ['name' => 'LOURDES', 'codigo_dane' => '54418'],
            ['name' => 'MUTISCUA', 'codigo_dane' => '54480'],
            ['name' => 'OCAÑA', 'codigo_dane' => '54498'],
            ['name' => 'PAMPLONA', 'codigo_dane' => '54518'],
            ['name' => 'PAMPLONITA', 'codigo_dane' => '54520'],
            ['name' => 'PUERTO SANTANDER', 'codigo_dane' => '54553'],
            ['name' => 'RAGONVALIA', 'codigo_dane' => '54599'],
            ['name' => 'SALAZAR', 'codigo_dane' => '54660'],
            ['name' => 'SAN CALIXTO', 'codigo_dane' => '54670'],
            ['name' => 'SAN CAYETANO', 'codigo_dane' => '54673'],
            ['name' => 'SANTIAGO', 'codigo_dane' => '54680'],
            ['name' => 'SARDINATA', 'codigo_dane' => '54720'],
            ['name' => 'SILOS', 'codigo_dane' => '54743'],
            ['name' => 'TEORAMA', 'codigo_dane' => '54800'],
            ['name' => 'TIBÚ', 'codigo_dane' => '54810'],
            ['name' => 'TOLEDO', 'codigo_dane' => '54820'],
            ['name' => 'VILLA CARO', 'codigo_dane' => '54871'],
            ['name' => 'VILLA DEL ROSARIO', 'codigo_dane' => '54874'],
            ['name' => 'ARMENIA', 'codigo_dane' => '63001'],
            ['name' => 'BUENAVISTA', 'codigo_dane' => '63111'],
            ['name' => 'CALARCÁ', 'codigo_dane' => '63130'],
            ['name' => 'CIRCASIA', 'codigo_dane' => '63190'],
            ['name' => 'CÓRDOBA', 'codigo_dane' => '63212'],
            ['name' => 'FILANDIA', 'codigo_dane' => '63272'],
            ['name' => 'GÉNOVA', 'codigo_dane' => '63302'],
            ['name' => 'LA TEBAIDA', 'codigo_dane' => '63401'],
            ['name' => 'MONTENEGRO', 'codigo_dane' => '63470'],
            ['name' => 'PIJAO', 'codigo_dane' => '63548'],
            ['name' => 'QUIMBAYA', 'codigo_dane' => '63594'],
            ['name' => 'SALENTO', 'codigo_dane' => '63690'],
            ['name' => 'PEREIRA', 'codigo_dane' => '66001'],
            ['name' => 'APÍA', 'codigo_dane' => '66045'],
            ['name' => 'BALBOA', 'codigo_dane' => '66075'],
            ['name' => 'BELÉN DE UMBRÍA', 'codigo_dane' => '66088'],
            ['name' => 'DOSQUEBRADAS', 'codigo_dane' => '66170'],
            ['name' => 'GUÁTICA', 'codigo_dane' => '66318'],
            ['name' => 'LA CELIA', 'codigo_dane' => '66383'],
            ['name' => 'LA VIRGINIA', 'codigo_dane' => '66400'],
            ['name' => 'MARSELLA', 'codigo_dane' => '66440'],
            ['name' => 'MISTRATÓ', 'codigo_dane' => '66456'],
            ['name' => 'PUEBLO RICO', 'codigo_dane' => '66572'],
            ['name' => 'QUINCHÍA', 'codigo_dane' => '66594'],
            ['name' => 'SANTA ROSA DE CABAL', 'codigo_dane' => '66682'],
            ['name' => 'SANTUARIO', 'codigo_dane' => '66687'],
            ['name' => 'BUCARAMANGA', 'codigo_dane' => '68001'],
            ['name' => 'AGUADA', 'codigo_dane' => '68013'],
            ['name' => 'ALBANIA', 'codigo_dane' => '68020'],
            ['name' => 'ARATOCA', 'codigo_dane' => '68051'],
            ['name' => 'BARBOSA', 'codigo_dane' => '68077'],
            ['name' => 'BARICHARA', 'codigo_dane' => '68079'],
            ['name' => 'BARRANCABERMEJA', 'codigo_dane' => '68081'],
            ['name' => 'BETULIA', 'codigo_dane' => '68092'],
            ['name' => 'BOLÍVAR', 'codigo_dane' => '68101'],
            ['name' => 'CABRERA', 'codigo_dane' => '68121'],
            ['name' => 'CALIFORNIA', 'codigo_dane' => '68132'],
            ['name' => 'CAPITANEJO', 'codigo_dane' => '68147'],
            ['name' => 'CARCASÍ', 'codigo_dane' => '68152'],
            ['name' => 'CEPITÁ', 'codigo_dane' => '68160'],
            ['name' => 'CERRITO', 'codigo_dane' => '68162'],
            ['name' => 'CHARALÁ', 'codigo_dane' => '68167'],
            ['name' => 'CHARTA', 'codigo_dane' => '68169'],
            ['name' => 'CHIMA', 'codigo_dane' => '68176'],
            ['name' => 'CHIPATÁ', 'codigo_dane' => '68179'],
            ['name' => 'CIMITARRA', 'codigo_dane' => '68190'],
            ['name' => 'CONCEPCIÓN', 'codigo_dane' => '68207'],
            ['name' => 'CONFINES', 'codigo_dane' => '68209'],
            ['name' => 'CONTRATACIÓN', 'codigo_dane' => '68211'],
            ['name' => 'COROMORO', 'codigo_dane' => '68217'],
            ['name' => 'CURITÍ', 'codigo_dane' => '68229'],
            ['name' => 'EL CARMEN DE CHUCURÍ', 'codigo_dane' => '68235'],
            ['name' => 'EL GUACAMAYO', 'codigo_dane' => '68245'],
            ['name' => 'EL PEÑÓN', 'codigo_dane' => '68250'],
            ['name' => 'EL PLAYÓN', 'codigo_dane' => '68255'],
            ['name' => 'ENCINO', 'codigo_dane' => '68264'],
            ['name' => 'ENCISO', 'codigo_dane' => '68266'],
            ['name' => 'FLORIÁN', 'codigo_dane' => '68271'],
            ['name' => 'FLORIDABLANCA', 'codigo_dane' => '68276'],
            ['name' => 'GALÁN', 'codigo_dane' => '68296'],
            ['name' => 'GÁMBITA', 'codigo_dane' => '68298'],
            ['name' => 'GIRÓN', 'codigo_dane' => '68307'],
            ['name' => 'GUACA', 'codigo_dane' => '68318'],
            ['name' => 'GUADALUPE', 'codigo_dane' => '68320'],
            ['name' => 'GUAPOTÁ', 'codigo_dane' => '68322'],
            ['name' => 'GUAVATÁ', 'codigo_dane' => '68324'],
            ['name' => 'GÜEPSA', 'codigo_dane' => '68327'],
            ['name' => 'HATO', 'codigo_dane' => '68344'],
            ['name' => 'JESÚS MARÍA', 'codigo_dane' => '68368'],
            ['name' => 'JORDÁN', 'codigo_dane' => '68370'],
            ['name' => 'LA BELLEZA', 'codigo_dane' => '68377'],
            ['name' => 'LANDÁZURI', 'codigo_dane' => '68385'],
            ['name' => 'LA PAZ', 'codigo_dane' => '68397'],
            ['name' => 'LEBRIJA', 'codigo_dane' => '68406'],
            ['name' => 'LOS SANTOS', 'codigo_dane' => '68418'],
            ['name' => 'MACARAVITA', 'codigo_dane' => '68425'],
            ['name' => 'MÁLAGA', 'codigo_dane' => '68432'],
            ['name' => 'MATANZA', 'codigo_dane' => '68444'],
            ['name' => 'MOGOTES', 'codigo_dane' => '68464'],
            ['name' => 'MOLAGAVITA', 'codigo_dane' => '68468'],
            ['name' => 'OCAMONTE', 'codigo_dane' => '68498'],
            ['name' => 'OIBA', 'codigo_dane' => '68500'],
            ['name' => 'ONZAGA', 'codigo_dane' => '68502'],
            ['name' => 'PALMAR', 'codigo_dane' => '68522'],
            ['name' => 'PALMAS DEL SOCORRO', 'codigo_dane' => '68524'],
            ['name' => 'PÁRAMO', 'codigo_dane' => '68533'],
            ['name' => 'PIEDECUESTA', 'codigo_dane' => '68547'],
            ['name' => 'PINCHOTE', 'codigo_dane' => '68549'],
            ['name' => 'PUENTE NACIONAL', 'codigo_dane' => '68572'],
            ['name' => 'PUERTO PARRA', 'codigo_dane' => '68573'],
            ['name' => 'PUERTO WILCHES', 'codigo_dane' => '68575'],
            ['name' => 'RIONEGRO', 'codigo_dane' => '68615'],
            ['name' => 'SABANA DE TORRES', 'codigo_dane' => '68655'],
            ['name' => 'SAN ANDRÉS', 'codigo_dane' => '68669'],
            ['name' => 'SAN BENITO', 'codigo_dane' => '68673'],
            ['name' => 'SAN GIL', 'codigo_dane' => '68679'],
            ['name' => 'SAN JOAQUÍN', 'codigo_dane' => '68682'],
            ['name' => 'SAN JOSÉ DE MIRANDA', 'codigo_dane' => '68684'],
            ['name' => 'SAN MIGUEL', 'codigo_dane' => '68686'],
            ['name' => 'SAN VICENTE DE CHUCURÍ', 'codigo_dane' => '68689'],
            ['name' => 'SANTA BÁRBARA', 'codigo_dane' => '68705'],
            ['name' => 'SANTA HELENA DEL OPÓN', 'codigo_dane' => '68720'],
            ['name' => 'SIMACOTA', 'codigo_dane' => '68745'],
            ['name' => 'SOCORRO', 'codigo_dane' => '68755'],
            ['name' => 'SUAITA', 'codigo_dane' => '68770'],
            ['name' => 'SUCRE', 'codigo_dane' => '68773'],
            ['name' => 'SURATÁ', 'codigo_dane' => '68780'],
            ['name' => 'TONA', 'codigo_dane' => '68820'],
            ['name' => 'VALLE DE SAN JOSÉ', 'codigo_dane' => '68855'],
            ['name' => 'VÉLEZ', 'codigo_dane' => '68861'],
            ['name' => 'VETAS', 'codigo_dane' => '68867'],
            ['name' => 'VILLANUEVA', 'codigo_dane' => '68872'],
            ['name' => 'ZAPATOCA', 'codigo_dane' => '68895'],
            ['name' => 'SINCELEJO', 'codigo_dane' => '70001'],
            ['name' => 'BUENAVISTA', 'codigo_dane' => '70110'],
            ['name' => 'CAIMITO', 'codigo_dane' => '70124'],
            ['name' => 'COLOSÓ', 'codigo_dane' => '70204'],
            ['name' => 'COROZAL', 'codigo_dane' => '70215'],
            ['name' => 'COVEÑAS', 'codigo_dane' => '70221'],
            ['name' => 'CHALÁN', 'codigo_dane' => '70230'],
            ['name' => 'EL ROBLE', 'codigo_dane' => '70233'],
            ['name' => 'GALERAS', 'codigo_dane' => '70235'],
            ['name' => 'GUARANDA', 'codigo_dane' => '70265'],
            ['name' => 'LA UNIÓN', 'codigo_dane' => '70400'],
            ['name' => 'LOS PALMITOS', 'codigo_dane' => '70418'],
            ['name' => 'MAJAGUAL', 'codigo_dane' => '70429'],
            ['name' => 'MORROA', 'codigo_dane' => '70473'],
            ['name' => 'OVEJAS', 'codigo_dane' => '70508'],
            ['name' => 'PALMITO', 'codigo_dane' => '70523'],
            ['name' => 'SAMPUÉS', 'codigo_dane' => '70670'],
            ['name' => 'SAN BENITO ABAD', 'codigo_dane' => '70678'],
            ['name' => 'SAN JUAN DE BETULIA', 'codigo_dane' => '70702'],
            ['name' => 'SAN MARCOS', 'codigo_dane' => '70708'],
            ['name' => 'SAN ONOFRE', 'codigo_dane' => '70713'],
            ['name' => 'SAN PEDRO', 'codigo_dane' => '70717'],
            ['name' => 'SAN LUIS DE SINCÉ', 'codigo_dane' => '70742'],
            ['name' => 'SUCRE', 'codigo_dane' => '70771'],
            ['name' => 'SANTIAGO DE TOLÚ', 'codigo_dane' => '70820'],
            ['name' => 'SAN JOSÉ DE TOLUVIEJO', 'codigo_dane' => '70823'],
            ['name' => 'IBAGUÉ', 'codigo_dane' => '73001'],
            ['name' => 'ALPUJARRA', 'codigo_dane' => '73024'],
            ['name' => 'ALVARADO', 'codigo_dane' => '73026'],
            ['name' => 'AMBALEMA', 'codigo_dane' => '73030'],
            ['name' => 'ANZOÁTEGUI', 'codigo_dane' => '73043'],
            ['name' => 'ARMERO', 'codigo_dane' => '73055'],
            ['name' => 'ATACO', 'codigo_dane' => '73067'],
            ['name' => 'CAJAMARCA', 'codigo_dane' => '73124'],
            ['name' => 'CARMEN DE APICALÁ', 'codigo_dane' => '73148'],
            ['name' => 'CASABIANCA', 'codigo_dane' => '73152'],
            ['name' => 'CHAPARRAL', 'codigo_dane' => '73168'],
            ['name' => 'COELLO', 'codigo_dane' => '73200'],
            ['name' => 'COYAIMA', 'codigo_dane' => '73217'],
            ['name' => 'CUNDAY', 'codigo_dane' => '73226'],
            ['name' => 'DOLORES', 'codigo_dane' => '73236'],
            ['name' => 'ESPINAL', 'codigo_dane' => '73268'],
            ['name' => 'FALAN', 'codigo_dane' => '73270'],
            ['name' => 'FLANDES', 'codigo_dane' => '73275'],
            ['name' => 'FRESNO', 'codigo_dane' => '73283'],
            ['name' => 'GUAMO', 'codigo_dane' => '73319'],
            ['name' => 'HERVEO', 'codigo_dane' => '73347'],
            ['name' => 'HONDA', 'codigo_dane' => '73349'],
            ['name' => 'ICONONZO', 'codigo_dane' => '73352'],
            ['name' => 'LÉRIDA', 'codigo_dane' => '73408'],
            ['name' => 'LÍBANO', 'codigo_dane' => '73411'],
            ['name' => 'SAN SEBASTIÁN DE MARIQUITA', 'codigo_dane' => '73443'],
            ['name' => 'MELGAR', 'codigo_dane' => '73449'],
            ['name' => 'MURILLO', 'codigo_dane' => '73461'],
            ['name' => 'NATAGAIMA', 'codigo_dane' => '73483'],
            ['name' => 'ORTEGA', 'codigo_dane' => '73504'],
            ['name' => 'PALOCABILDO', 'codigo_dane' => '73520'],
            ['name' => 'PIEDRAS', 'codigo_dane' => '73547'],
            ['name' => 'PLANADAS', 'codigo_dane' => '73555'],
            ['name' => 'PRADO', 'codigo_dane' => '73563'],
            ['name' => 'PURIFICACIÓN', 'codigo_dane' => '73585'],
            ['name' => 'RIOBLANCO', 'codigo_dane' => '73616'],
            ['name' => 'RONCESVALLES', 'codigo_dane' => '73622'],
            ['name' => 'ROVIRA', 'codigo_dane' => '73624'],
            ['name' => 'SALDAÑA', 'codigo_dane' => '73671'],
            ['name' => 'SAN ANTONIO', 'codigo_dane' => '73675'],
            ['name' => 'SAN LUIS', 'codigo_dane' => '73678'],
            ['name' => 'SANTA ISABEL', 'codigo_dane' => '73686'],
            ['name' => 'SUÁREZ', 'codigo_dane' => '73770'],
            ['name' => 'VALLE DE SAN JUAN', 'codigo_dane' => '73854'],
            ['name' => 'VENADILLO', 'codigo_dane' => '73861'],
            ['name' => 'VILLAHERMOSA', 'codigo_dane' => '73870'],
            ['name' => 'VILLARRICA', 'codigo_dane' => '73873'],
            ['name' => 'SANTIAGO DE CALI', 'codigo_dane' => '76001'],
            ['name' => 'ALCALÁ', 'codigo_dane' => '76020'],
            ['name' => 'ANDALUCÍA', 'codigo_dane' => '76036'],
            ['name' => 'ANSERMANUEVO', 'codigo_dane' => '76041'],
            ['name' => 'ARGELIA', 'codigo_dane' => '76054'],
            ['name' => 'BOLÍVAR', 'codigo_dane' => '76100'],
            ['name' => 'BUENAVENTURA', 'codigo_dane' => '76109'],
            ['name' => 'GUADALAJARA DE BUGA', 'codigo_dane' => '76111'],
            ['name' => 'BUGALAGRANDE', 'codigo_dane' => '76113'],
            ['name' => 'CAICEDONIA', 'codigo_dane' => '76122'],
            ['name' => 'CALIMA', 'codigo_dane' => '76126'],
            ['name' => 'CANDELARIA', 'codigo_dane' => '76130'],
            ['name' => 'CARTAGO', 'codigo_dane' => '76147'],
            ['name' => 'DAGUA', 'codigo_dane' => '76233'],
            ['name' => 'EL ÁGUILA', 'codigo_dane' => '76243'],
            ['name' => 'EL CAIRO', 'codigo_dane' => '76246'],
            ['name' => 'EL CERRITO', 'codigo_dane' => '76248'],
            ['name' => 'EL DOVIO', 'codigo_dane' => '76250'],
            ['name' => 'FLORIDA', 'codigo_dane' => '76275'],
            ['name' => 'GINEBRA', 'codigo_dane' => '76306'],
            ['name' => 'GUACARÍ', 'codigo_dane' => '76318'],
            ['name' => 'JAMUNDÍ', 'codigo_dane' => '76364'],
            ['name' => 'LA CUMBRE', 'codigo_dane' => '76377'],
            ['name' => 'LA UNIÓN', 'codigo_dane' => '76400'],
            ['name' => 'LA VICTORIA', 'codigo_dane' => '76403'],
            ['name' => 'OBANDO', 'codigo_dane' => '76497'],
            ['name' => 'PALMIRA', 'codigo_dane' => '76520'],
            ['name' => 'PRADERA', 'codigo_dane' => '76563'],
            ['name' => 'RESTREPO', 'codigo_dane' => '76606'],
            ['name' => 'RIOFRÍO', 'codigo_dane' => '76616'],
            ['name' => 'ROLDANILLO', 'codigo_dane' => '76622'],
            ['name' => 'SAN PEDRO', 'codigo_dane' => '76670'],
            ['name' => 'SEVILLA', 'codigo_dane' => '76736'],
            ['name' => 'TORO', 'codigo_dane' => '76823'],
            ['name' => 'TRUJILLO', 'codigo_dane' => '76828'],
            ['name' => 'TULUÁ', 'codigo_dane' => '76834'],
            ['name' => 'ULLOA', 'codigo_dane' => '76845'],
            ['name' => 'VERSALLES', 'codigo_dane' => '76863'],
            ['name' => 'VIJES', 'codigo_dane' => '76869'],
            ['name' => 'YOTOCO', 'codigo_dane' => '76890'],
            ['name' => 'YUMBO', 'codigo_dane' => '76892'],
            ['name' => 'ZARZAL', 'codigo_dane' => '76895'],
            ['name' => 'ARAUCA', 'codigo_dane' => '81001'],
            ['name' => 'ARAUQUITA', 'codigo_dane' => '81065'],
            ['name' => 'CRAVO NORTE', 'codigo_dane' => '81220'],
            ['name' => 'FORTUL', 'codigo_dane' => '81300'],
            ['name' => 'PUERTO RONDÓN', 'codigo_dane' => '81591'],
            ['name' => 'SARAVENA', 'codigo_dane' => '81736'],
            ['name' => 'TAME', 'codigo_dane' => '81794'],
            ['name' => 'YOPAL', 'codigo_dane' => '85001'],
            ['name' => 'AGUAZUL', 'codigo_dane' => '85010'],
            ['name' => 'CHÁMEZA', 'codigo_dane' => '85015'],
            ['name' => 'HATO COROZAL', 'codigo_dane' => '85125'],
            ['name' => 'LA SALINA', 'codigo_dane' => '85136'],
            ['name' => 'MANÍ', 'codigo_dane' => '85139'],
            ['name' => 'MONTERREY', 'codigo_dane' => '85162'],
            ['name' => 'NUNCHÍA', 'codigo_dane' => '85225'],
            ['name' => 'OROCUÉ', 'codigo_dane' => '85230'],
            ['name' => 'PAZ DE ARIPORO', 'codigo_dane' => '85250'],
            ['name' => 'PORE', 'codigo_dane' => '85263'],
            ['name' => 'RECETOR', 'codigo_dane' => '85279'],
            ['name' => 'SABANALARGA', 'codigo_dane' => '85300'],
            ['name' => 'SÁCAMA', 'codigo_dane' => '85315'],
            ['name' => 'SAN LUIS DE PALENQUE', 'codigo_dane' => '85325'],
            ['name' => 'TÁMARA', 'codigo_dane' => '85400'],
            ['name' => 'TAURAMENA', 'codigo_dane' => '85410'],
            ['name' => 'TRINIDAD', 'codigo_dane' => '85430'],
            ['name' => 'VILLANUEVA', 'codigo_dane' => '85440'],
            ['name' => 'MOCOA', 'codigo_dane' => '86001'],
            ['name' => 'COLÓN', 'codigo_dane' => '86219'],
            ['name' => 'ORITO', 'codigo_dane' => '86320'],
            ['name' => 'PUERTO ASÍS', 'codigo_dane' => '86568'],
            ['name' => 'PUERTO CAICEDO', 'codigo_dane' => '86569'],
            ['name' => 'PUERTO GUZMÁN', 'codigo_dane' => '86571'],
            ['name' => 'PUERTO LEGUÍZAMO', 'codigo_dane' => '86573'],
            ['name' => 'SIBUNDOY', 'codigo_dane' => '86749'],
            ['name' => 'SAN FRANCISCO', 'codigo_dane' => '86755'],
            ['name' => 'SAN MIGUEL', 'codigo_dane' => '86757'],
            ['name' => 'SANTIAGO', 'codigo_dane' => '86760'],
            ['name' => 'VALLE DEL GUAMUEZ', 'codigo_dane' => '86865'],
            ['name' => 'VILLAGARZÓN', 'codigo_dane' => '86885'],
            ['name' => 'PROVIDENCIA', 'codigo_dane' => '88564'],
            ['name' => 'LETICIA', 'codigo_dane' => '91001'],
            ['name' => 'PUERTO NARIÑO', 'codigo_dane' => '91540'],
            ['name' => 'INÍRIDA', 'codigo_dane' => '94001'],
            ['name' => 'BARRANCOMINAS', 'codigo_dane' => '94343'],
            ['name' => 'SAN JOSÉ DEL GUAVIARE', 'codigo_dane' => '95001'],
            ['name' => 'CALAMAR', 'codigo_dane' => '95015'],
            ['name' => 'EL RETORNO', 'codigo_dane' => '95025'],
            ['name' => 'MIRAFLORES', 'codigo_dane' => '95200'],
            ['name' => 'MITÚ', 'codigo_dane' => '97001'],
            ['name' => 'CARURÚ', 'codigo_dane' => '97161'],
            ['name' => 'TARAIRA', 'codigo_dane' => '97666'],
            ['name' => 'PUERTO CARREÑO', 'codigo_dane' => '99001'],
            ['name' => 'LA PRIMAVERA', 'codigo_dane' => '99524'],
            ['name' => 'SANTA ROSALÍA', 'codigo_dane' => '99624'],
            ['name' => 'CUMARIBO', 'codigo_dane' => '99773'],
        ];

        // Mapear departamento_id desde la tabla 'departamentos'
        $deptMap = DB::table('departamentos')->pluck('id', 'codigo_dane'); // ['05' => 1, ...]

        $array = array_map(function($r) use ($deptMap) {
            $depCode = substr($r['codigo_dane'], 0, 2);
            if (!isset($deptMap[$depCode])) {
                throw new \RuntimeException("Departamento no encontrado para código DANE: {$depCode}");
            }
            $r['departamentos_id'] = $deptMap[$depCode];
            return $r;
        }, $array);

        DB::table('municipios')->insert($array);
    }
}
